# Looking at the 5 minute weather obs
- want to see how the csv are organised
- how to open the csv files
- get the correct station IDs for the areas I want

## Greater Brisbane

In [3]:
import zipfile
from pathlib import Path

zip_path = Path("/home/565/pv3484/aus_substation_electricity/data/raw_data/GREATER_BRISBANE_obs/039089-040861.zip")
extract_dir = zip_path.with_suffix('')  # same name, no .zip

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_dir)

In [13]:
stations = pd.read_csv(
    extract_dir / "HD01D_StnDet_9999999910707406.txt",
    sep=",",
    header=None,
    engine="python",
    encoding="utf-8",
    skiprows=1
)

stations.head()

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,st,39122,39,HERON ISLAND RES STN,01/1956,,-23.4417,151.9125,GPS,QLD,...,94386,2021,2024,99,99,1,0,*,0,#
1,st,39123,39,GLADSTONE RADAR,01/1957,,-23.8553,151.2628,GPS,QLD,...,94380,2003,2024,99,99,1,0,*,*,#
2,st,39128,39,BUNDABERG AERO,01/1942,,-24.9069,152.3230,SURVEY,QLD,...,94387,2010,2024,99,99,*,0,*,*,#
3,st,39326,39,GLADSTONE AIRPORT,10/1993,,-23.8697,151.2214,GPS,QLD,...,94381,2003,2024,99,99,1,0,*,*,#
4,st,40004,40,AMBERLEY AMO,01/1941,,-27.6297,152.7111,GPS,QLD,...,94568,2000,2024,99,96,4,0,*,*,#

In [14]:
stations.columns = [
    "record_type", "site_id", "site_num", "site_name", "start_date",
    "lat", "lon", "location_method", "state", "elev", "bar_ht", "wmo_id",
    "start_year", "end_year", "percent_complete", "percent_quality",
    "has_rain", "has_temp", "unknown1", "has_wind", "unknown2", "end_marker"
]

In [17]:
stations.head(10)

,record_type,site_id,site_num,site_name,start_date,lat,lon,location_method,state,elev,...,start_year,end_year,percent_complete,percent_quality,has_rain,has_temp,unknown1,has_wind,unknown2,end_marker
0,st,39122,39,HERON ISLAND RES STN,01/1956,,-23.4417,151.9125,GPS,QLD,...,94386,2021,2024,99,99,1,0,*,0,#
1,st,39123,39,GLADSTONE RADAR,01/1957,,-23.8553,151.2628,GPS,QLD,...,94380,2003,2024,99,99,1,0,*,*,#
2,st,39128,39,BUNDABERG AERO,01/1942,,-24.9069,152.3230,SURVEY,QLD,...,94387,2010,2024,99,99,*,0,*,*,#
3,st,39326,39,GLADSTONE AIRPORT,10/1993,,-23.8697,151.2214,GPS,QLD,...,94381,2003,2024,99,99,1,0,*,*,#
4,st,40004,40,AMBERLEY AMO,01/1941,,-27.6297,152.7111,GPS,QLD,...,94568,2000,2024,99,96,4,0,*,*,#
5,st,40043,40,CAPE MORETON LIGHTHOUSE,01/1869,,-27.0314,153.4661,GPS,QLD,...,94594,2004,2024,99,99,1,0,*,*,#
6,st,40068,40,DOUBLE ISLAND POINT LIGHTHOUSE,01/1891,,-25.9319,153.1906,GPS,QLD,...,94584,2004,2024,99,99,1,0,*,*,#
7,st,40082,40,UNIVERSITY OF QUEENSLAND GATTON,01/1897,,-27.5436,152.3375,GPS,QLD,...,94562,2010,2024,99,99,*,0,*,*,#
8,st,40093,40,GYMPIE,01/1870,,-26.1831,152.6414,GPS,QLD,...,94566,2010,2024,99,99,*,0,*,*,#
9,st,40126,40,MARYBOROUGH,01/1870,,-25.5132,152.7152,SURVEY,QLD,...,94567,2011,2024,99,99,*,0,*,*,#